config/routes.rb
Rails.application.routes.draw do
  root "pasos#index"

  resources :pasos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/paso.rb
class Paso < ApplicationRecord
  validates :day, presence: true
  validates :destination, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pasos_controller.rb
class PasosController < ApplicationController
  def index
    @pasos = Paso.all
  end

  def show
    @paso = Paso.find(params[:id])
  end

  def new
    @paso = Paso.new()
  end

  def create
    @paso = Paso.new(paso_params)

    if @paso.save
      redirect_to @paso
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @paso = Paso.find(params[:id])
  end

  def update
    @paso = Paso.find(params[:id])

    if @paso.update(paso_params)
      redirect_to @paso
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @paso = Paso.find(params[:id])
    @paso.destroy

    redirect_to pasos_path, status: :see_other
  end

  private

  def paso_params
    params.require(:paso).permit(:day, :destination)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pasos_helper.rb
module PasosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleRails2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pasos/_form.html.erb
<%= form_with model: @paso do |form| %>
  <div>
    <%= form.label :day %><br>
    <%= form.date_select :day %>
    <% @paso.errors.full_messages_for(:day).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <br/>

  <div>
    <%= form.label :destination %><br/>
    <%= form.text_field :destination %>
    <% @paso.errors.full_messages_for(:destination).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pasos/edit.html.erb
<h1>Edit Paso</h1>

<%= render "form", paso: @paso %>

app/views/pasos/index.html.erb
<h1>Pasos</h1>

<div data-controller="pasos">
  <input data-pasos-target="query" type="text" placeholder="Search...">
  <button data-action="click->pasos#search">Search</button>

  <ul>
    <% @pasos.each do |paso| %>
      <li data-pasos-target="paso">
        <%= link_to "#{paso.destination} #{paso.day}", paso %>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to "Create paso", new_paso_path %>

app/views/pasos/new.html.erb
<h1>New Paso</h1>

<%= form_with model: @paso do |form| %>
  <div>
    <%= form.label :day %><br>
    <%= form.date_select :day %>
    <% @paso.errors.full_messages_for(:day).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <br/>

  <div>
    <%= form.label :destination %><br/>
    <%= form.text_field :destination %>
    <% @paso.errors.full_messages_for(:destination).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pasos/show.html.erb
<h3><%= @paso.destination %>: <%= @paso.day %></h3>

<ul>
  <li><%= link_to "Show all", pasos_path %></li>
  <li><%= link_to "Edit", edit_paso_path(@paso) %></li>
  <li><%= link_to "Delete", paso_path(@paso), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    }%></li>
</ul>